name: OWASP ZAP Scan (GitHub Native)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and start app
        run: |
          npm install
          npm start &
          sleep 25

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: http://localhost:3000
          allow_issue_writing: false
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: report_html/report.html

          # Updated: Final artifact name fix
