name: OWASP ZAP Scan (No Docker)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and start app
        run: |
          npm install
          npm start &
          sleep 25

      - name: Install ZAP CLI
        run: |
          sudo snap install zaproxy --classic

      - name: Run ZAP Spider Scan
        run: |
          zaproxy -cmd -quickurl http://localhost:3000 -quickout zap_report.html -quickprogress

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
