name: OWASP ZAP Scan (Artifact Fix)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    outputs:
      report_path: ${{ steps.save_report.outputs.report_path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and start app
        run: |
          npm install
          npm start &
          sleep 25

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: http://localhost:3000
          allow_issue_writing: false
          cmd_options: '-a'

      - name: Confirm report exists
        id: save_report
        run: |
          ls -l report_html
          echo "report_path=report_html/report.html" >> $GITHUB_OUTPUT

  upload_report:
    needs: zap_scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload final ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-artifact-clean
          path: report_html/report.html
