name: OWASP ZAP Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and start app
        run: |
          npm install
          npm start &
          sleep 25

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network="host" -t owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:3000 \
            -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
