name: OWASP ZAP Scan (Final Report Fix)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and start app
        run: |
          npm install
          npm start &
          sleep 25

      - name: Pull ZAP CLI (from GitHub Container Registry)
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Scan and Save Report
        run: |
          mkdir -p zap-output
          docker run --network="host" -v $(pwd)/zap-output:/zap/output \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:3000 \
            -r /zap/output/zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report-final
          path: zap-output/zap_report.html
